Repository laminas/laminas-code, pull requests merged in 2020-11, with the labels that each got.

#31 Modify the examples to make them compatible with PSR-12
  docs/book/generator/examples.md
Labels: Documentation

#50 Some constants are not rendered properly depending on environment values
  src/Generator/ValueGenerator.php
  test/Generator/ValueGeneratorTest.php
Labels: Bug

#55 use 8.0 instead of nightly on travis
  .travis.yml
Labels: Enhancement
