Repository laminas/laminas-code, pull requests merged in 2021-05, with the labels that each got.

#81 Fix `DocBlockGenerator` formatting issue when docblock long description is not available
  src/Generator/DocBlockGenerator.php
  test/Generator/DocBlockGeneratorTest.php
Labels: Bug

#84 Remove `CHANGELOG.md` to simplify release workflow
  CHANGELOG.md
Labels: Documentation, Enhancement

#85 Normalize composer
  composer.json
Labels: Enhancement
