Repository laminas/laminas-code, pull requests merged in 2022-11, with the labels that each got.

#149 Add support for standalone `true`, `false` and `null` types
  src/Generator/TypeGenerator/AtomicType.php
  test/Generator/TypeGeneratorTest.php
Labels: Enhancement

#152 Removed dead execution branches
  src/Generator/TypeGenerator.php
  src/Generator/TypeGenerator/AtomicType.php
Labels: Enhancement

#153 Deprecating all `::fromArray()` methods in in the package
  docs/book/generator/examples.md
  docs/book/generator/reference.md
  psalm-baseline.xml
  src/DeclareStatement.php
  src/Generator/ClassGenerator.php
  src/Generator/DocBlockGenerator.php
  src/Generator/FileGenerator.php
  src/Generator/InterfaceGenerator.php
  src/Generator/MethodGenerator.php
  src/Generator/ParameterGenerator.php
  src/Generator/PropertyGenerator.php
  src/Generator/TraitGenerator.php
Labels: Documentation, Enhancement, Feature Removal

#154 Drop PHP 7.4 and PHP 8.0 support
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/docs-build.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  .github/workflows/release-on-milestone-closed.yml
  composer.json
  composer.lock
  polyfill/ReflectionEnumPolyfill.php
  psalm-baseline.xml
  src/Generator/AbstractGenerator.php
  src/Generator/ClassGenerator.php
  src/Generator/DocBlock/Tag.php
  src/Generator/DocBlock/Tag/AbstractTypeableTag.php
  src/Generator/DocBlock/Tag/AuthorTag.php
  src/Generator/DocBlock/Tag/GenericTag.php
  src/Generator/DocBlock/Tag/LicenseTag.php
  src/Generator/DocBlock/Tag/MethodTag.php
  src/Generator/DocBlock/Tag/PropertyTag.php
  src/Generator/DocBlock/Tag/VarTag.php
  src/Generator/EnumGenerator/Cases/BackedCases.php
  src/Generator/EnumGenerator/Cases/CaseFactory.php
  src/Generator/EnumGenerator/Cases/PureCases.php
  src/Generator/EnumGenerator/EnumGenerator.php
  src/Generator/FileGenerator.php
  src/Generator/InterfaceGenerator.php
  src/Generator/MethodGenerator.php
  src/Generator/ParameterGenerator.php
  src/Generator/PropertyGenerator.php
  src/Generator/TraitUsageGenerator.php
  src/Generator/TraitUsageInterface.php
  src/Generator/ValueGenerator.php
  src/Generic/Prototype/PrototypeClassFactory.php
  src/Generic/Prototype/PrototypeGenericInterface.php
  src/Reflection/ClassReflection.php
  src/Reflection/DocBlock/Tag/AuthorTag.php
  src/Reflection/DocBlock/Tag/GenericTag.php
  src/Reflection/DocBlock/Tag/LicenseTag.php
  src/Reflection/DocBlock/Tag/MethodTag.php
  src/Reflection/DocBlock/Tag/ParamTag.php
  src/Reflection/DocBlock/Tag/PhpDocTypedTagInterface.php
  src/Reflection/DocBlock/Tag/PropertyTag.php
  src/Reflection/DocBlock/Tag/ReturnTag.php
  src/Reflection/DocBlock/Tag/ThrowsTag.php
  src/Reflection/DocBlock/Tag/VarTag.php
  src/Reflection/FunctionReflection.php
  src/Reflection/MethodReflection.php
  src/Reflection/ParameterReflection.php
  test/Generator/MethodGeneratorTest.php
  test/Generator/ParameterGeneratorTest.php
  test/Generator/ValueGeneratorTest.php
  test/Reflection/ClassReflectionTest.php
Labels: Enhancement

#156 Fix generating final classes from reflection
  src/Generator/ClassGenerator.php
  test/Generator/ClassGeneratorTest.php
Labels: Bug

#147 Add support for readonly classes
  psalm-baseline.xml
  psalm.xml
  src/Generator/ClassGenerator.php
  test/Generator/ClassGeneratorTest.php
  test/Generator/TestAsset/ReadonlyClassWithPromotedParameter.php
Labels: Enhancement

#158 Use str_starts_with and str_contains where possible
  psalm-baseline.xml
  src/Generator/ClassGenerator.php
  src/Generator/DocBlock/TagManager.php
  src/Generator/TraitUsageGenerator.php
  src/Generator/TypeGenerator.php
  src/Generator/ValueGenerator.php
  test/Generator/TypeGeneratorTest.php
Labels: Enhancement

#161 Make the return-type of ClassReflection::getStartLine() explicit
  src/Reflection/ClassReflection.php
Labels: Documentation, Enhancement

#160 Use static data providers in preparation for PHPUnit 10
  test/Generator/EnumGeneratorTest.php
  test/Generator/MethodGeneratorTest.php
  test/Generator/ParameterGeneratorTest.php
  test/Generator/PropertyGeneratorTest.php
  test/Generator/TypeGeneratorTest.php
  test/Generator/ValueGeneratorTest.php
  test/Reflection/DocBlock/Tag/VarTagTest.php
  test/Reflection/ParameterReflectionTest.php
  test/Reflection/ReflectionDocBlockTagTest.php
Labels: Enhancement
